#ifndef INDEX_H
#define INDEX_H

#include "card_0.h"
#include "card_1.h"
#include "card_2.h"
#include "card_3.h"
#include "card_4.h"
#include "card_5.h"
#include "card_6.h"
#include "card_7.h"
#include "card_8.h"
#include "card_9.h"
#include "card_10.h"
#include "card_11.h"
#include "card_12.h"
#include "card_13.h"
#include "card_14.h"
#include "card_15.h"
#include "card_16.h"
#include "card_17.h"
#include "card_18.h"
#include "card_19.h"
#include "card_20.h"
#include "card_21.h"
#include "card_22.h"
#include "card_23.h"
#include "card_24.h"
#include "card_25.h"

#endif // INDEX_H
